#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
source "$SCRIPT_DIR/openshift_vars.sh"

#  Source StrongLoop shell utility functions.
source "$OPENSHIFT_DATA_DIR/strongloop/buildpack/lib/utils.sh"

#  Autodetect platform to setup StrongLoop env variables.
autodetect_platform

#  We moved the package.json file out of the way in pre_build, so that
#  the OpenShift git post-receive hook doesn't try and use the old npm
#  version to install the dependencies. Move it back in.
tmp_dir=${STRONGLOOP_TMPDIR:-"/tmp"}
tmp_package_json="$tmp_dir/package.json"
if [ -f "$tmp_package_json" ]; then
   #  Only overlay it if there is no current package.json file.
   [ -f "${OPENSHIFT_REPO_DIR}/package.json" ]  ||    \
      mv "$tmp_package_json" "${OPENSHIFT_REPO_DIR}/package.json"
fi


#  Install any package dependencies.
[ -z "$TMPDIR" ] && export TMPDIR="/tmp"
srcdir="$OPENSHIFT_REPO_DIR"
instdir="$OPENSHIFT_DATA_DIR"
install_package_dependencies "$srcdir" "$cache_dir" "$instdir"

