#!/bin/bash
#  This is a simple script and will be executed on your CI system if
#  available.  Otherwise it will execute while your application is stopped
#  before the build step.  This script gets executed directly, so it
#  could be python, php, ruby, etc.


SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
source "$SCRIPT_DIR/openshift_vars.sh"

if [ ! -d "$OPENSHIFT_DATA_DIR/strongloop/buildpack" ]; then
  mkdir -p "$OPENSHIFT_DATA_DIR/strongloop"
  pushd "$OPENSHIFT_DATA_DIR/strongloop" > /dev/null
  git clone "$github_repo" buildpack
  popd > /dev/null
fi


#  Source StrongLoop shell utility functions.
source "$OPENSHIFT_DATA_DIR/strongloop/buildpack/lib/utils.sh"

#  Autodetect platform.
autodetect_platform

#  Ensure StrongLoop Node version is installed. You can either pass a
#  StrongLoop Node version here or then you can edit the strongloop/VERSION
#  marker file. If no version is specified, the version in the marker file
#  if any is used or then the default StrongLoop Node version is installed.
echo ""
# TODO:  check re: repo dir so that it gets synced over to other gears.
install_strongloop_node "$install_dir" "$cache_dir"


#  We need to move the package.json file out of the way in pre_build, so
#  that the OpenShift git post-receive hook doesn't try and use the old
#  npm version to install the dependencies.
if [ -f "${OPENSHIFT_REPO_DIR}/package.json" ]; then
  mv "${OPENSHIFT_REPO_DIR}/package.json" ${STRONGLOOP_TMPDIR:-"/tmp"}
fi


